# Site settings
title: Security Reports
logo: "/img/logo.png"
email: your-email@domain.com
description: > # sdfsadf
 Security reports from Binary Security Department of inteligence, inside Sunset Inc. Threats should be take seriously, actions to contrarrest any breach of security or solve system weakness will be taken imediatly.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: /reports/:title
